export const CREATE = 'PROJECT/CREATE';
export const FETCH = 'PROJECT/FETCH';
export const FETCH_SUCCESS = 'PROJECT/FETCH_SUCCESS';
export const FETCH_REQUEST = 'PROJECT/FETCH_REQUEST';
export const FETCH_ERROR = 'PROJECT/FETCH_ERROR';
export const CLEAR = 'PROJECT/CLEAR';
export const SAVE_TO_HISTORY = 'PROJECT/SAVE_TO_HISTORY';
export const OPEN_SETTINGS = 'PROJECT/OPEN_SETTINGS';
export const CLOSE_SETTINGS = 'PROJECT/CLOSE_SETTINGS';

