export const RUN_METHOD = 'RUN_METHOD';
export const RUN_METHOD_REQUEST = 'RUN_METHOD/REQUEST';
export const RUN_METHOD_SUCCESS = 'RUN_METHOD/SUCCESS';
export const RUN_METHOD_FAILURE = 'RUN_METHOD/FAILURE';
